# TCL File Generated by Component Editor 9.1sp2
# Sun Dec 12 21:26:16 JST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pixelsimd "pixelsimd" v1.0
# | null 2010.12.12.21:26:16
# | 
# | 
# | D:/PROJECT/DE0/nios2_fpu/custom_intsr_pixel/pixelsimd.vhd
# | 
# |    ./pixelsimd.vhd syn, sim
# |    ./pixelsimd_blend_u8.vhd syn, sim
# |    ./pixelsimd_mult_s8xs10.vhd syn, sim
# |    ./pixelsimd_mult_u8xu8.vhd syn, sim
# |    ./pixelsimd_sat_u8.vhd syn, sim
# |    ./pixelsimd_yuvdec.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module pixelsimd
# | 
set_module_property NAME pixelsimd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME pixelsimd
set_module_property TOP_LEVEL_HDL_FILE pixelsimd.vhd
set_module_property TOP_LEVEL_HDL_MODULE pixelsimd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pixelsimd.vhd {SYNTHESIS SIMULATION}
add_file pixelsimd_blend_u8.vhd {SYNTHESIS SIMULATION}
add_file pixelsimd_mult_s8xs10.vhd {SYNTHESIS SIMULATION}
add_file pixelsimd_mult_u8xu8.vhd {SYNTHESIS SIMULATION}
add_file pixelsimd_sat_u8.vhd {SYNTHESIS SIMULATION}
add_file pixelsimd_yuvdec.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 8

set_interface_property nios_custom_instruction_slave_0 ENABLED true

add_interface_port nios_custom_instruction_slave_0 dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 datab datab Input 32
add_interface_port nios_custom_instruction_slave_0 result result Output 32
add_interface_port nios_custom_instruction_slave_0 clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave_0 reset reset Input 1
add_interface_port nios_custom_instruction_slave_0 start start Input 1
add_interface_port nios_custom_instruction_slave_0 done done Output 1
add_interface_port nios_custom_instruction_slave_0 n n Input 3
# | 
# +-----------------------------------
