# TCL File Generated by Component Editor 9.1sp2
# Thu Dec 30 12:09:11 JST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | mmcdma "mmcdma" v1.0
# | null 2010.12.30.12:09:11
# | 
# | 
# | D:/PROJECT/DE0/cineraria/mmcdma/avalonif_mmcdma.vhd
# | 
# |    ./avalonif_mmcdma.vhd syn, sim
# |    ./avalonif_mmc.vhd syn, sim
# |    ./dmamem.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module mmcdma
# | 
set_module_property NAME mmcdma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Peripherals
set_module_property DISPLAY_NAME mmcdma
set_module_property TOP_LEVEL_HDL_FILE avalonif_mmcdma.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalonif_mmcdma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalonif_mmcdma.vhd {SYNTHESIS SIMULATION}
add_file avalonif_mmc.vhd {SYNTHESIS SIMULATION}
add_file dmamem.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter SYSTEMCLOCKINFO INTEGER 0 ""
set_parameter_property SYSTEMCLOCKINFO SYSTEM_INFO {CLOCK_RATE clock_reset} 
set_parameter_property SYSTEMCLOCKINFO DISPLAY_NAME "Drive clock rate"
set_parameter_property SYSTEMCLOCKINFO UNITS Hertz

# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 associatedClock clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 2
set_interface_property s1 readWaitTime 2
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clock_reset
set_interface_property s1 ENABLED true

add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 8
add_interface_port s1 read read Input 1
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 write write Input 1
add_interface_port s1 writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end MMC_nCS export Output 1
add_interface_port conduit_end MMC_SCK export Output 1
add_interface_port conduit_end MMC_SDO export Output 1
add_interface_port conduit_end MMC_SDI export Input 1
add_interface_port conduit_end MMC_CD export Input 1
add_interface_port conduit_end MMC_WP export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint s1

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------
